mcp43h2_prod: 

  file_templates : ['fc@YYYY@@MM@@DD@@HH@+@LLL@grib_sfxs','fc@YYYY@@MM@@DD@@HH@+@LLL@grib2_fp']

  atos:
     path_template : 'ec:/snh/harmonie/mcp43h2_prod/@YYYY@/@MM@/@DD@/@HH@/mbr000/'

  domain : 
     name : 'METCOOP25D'
     resolution : 2500
     levels : 65

