hres: 
  file_templates : ['PFIFSDEOL+%LLLL']

  atos :
   path_template : '/scratch/sism/DEOL/%Y/%m/%d/%H/'

  lumi :
   hostname : lumi.csc.fi
   path_template : '/project/project_462000140/de_33050_common_data/LBC/IFS/%Y/%m/%d/%H/'

  domain : 
   name : 'DEOL'
   resolution : 9000
   levels : 137
