hres: 
  file_templates : ['PFIFSDEOL+@LLLL@']

  atos :
   path_template : '/scratch/sism/DEOL/@YYYY@/@MM@/@DD@/@HH@/'

  lumi :
   hostname : lumi.csc.fi
   path_template : '/project/project_462000140/de_33050_common_data/LBC/IFS/@YYYY@/@MM@/@DD@/@HH@/'

  domain : 
   name : 'DEOL'
   resolution : 9000
   levels : 137
